export { LoginPage } from './auth/login'
export { RegisterPage } from './auth/register'
export { ProfilePage } from './profile'
export { NewGamePage } from './game'
export { ErrorPage } from './error'
